CGSilent/Areas/Store/Controllers/StoreAdminController.cs
using CGSilent.Models;
using System.Collections;
using System.Web.Mvc;
using MongoDB.Bson;
using System;
using System.Web;
using MongoDB.Driver.GridFS;
using System.IO;
using System.Collections.Generic;
using System.Net; 
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using Microsoft.AspNet.Identity;
using PagedList;
using System.Drawing;
using System.Drawing.Imaging;

namespace CGSilent.Areas.Store.Controllers
{
    public class StoreAdminController : Controller
    {
        // GET: Article/Management
        enum StoreimageType { Galary, Image };

        [HttpGet]
        public ActionResult Index(int? page)
        {
            InsertSiteStatic(ObjectId.Empty, ObjectId.Empty, "Store");
            var pageNumber = page ?? 1;
            LoadArticlesAndStoresData(pageNumber);
            return View("StoreList");
        }


        [HttpGet]
        private void InsertSiteStatic(ObjectId ArticleId, ObjectId storeId, string pageName)
        {
            string strHostName = "";
            strHostName = Dns.GetHostName();
            IPHostEntry ipEntry = Dns.GetHostEntry(strHostName);
            UserRoles roles = new UserRoles();
            if (User.Identity.IsAuthenticated)
            {
                roles.Id = ObjectId.Parse(User.Identity.GetUserId());
                roles = roles.LoadDataByUserId();
            }
            else
            {
                roles.Id = ObjectId.Empty;
            }
            //افزودن آمار بازدید از سایت
            if (roles != null)
            {
                SiteStatics ss = new SiteStatics();
                ss.CreatedDate = DateTime.Now.ToString("s");
                ss.PageName = pageName;
                ss.ArticleId = ArticleId;
                ss.StoreId = storeId;
                if (User.Identity.IsAuthenticated)
                    ss.UserIdOrIp = User.Identity.GetUserId();
                else
                    ss.UserIdOrIp = Convert.ToString(ipEntry.AddressList[1]);

                if (roles.Roles != null)
                    for (int i = 0; i < roles.Roles.Length; i++)
                    {
                        ss.RoleName = roles.Roles[i];
                        ss.Insert();
                    }
                else
                {
                    ss.Insert();
                }
            }
        }

        #region LayoutFunctions

        [ChildActionOnly]
        public ActionResult SlideShow()
        {
            Articles al = new Articles();
            string SlideId = "5a526a33e290b819dc102a35";
            return PartialView("~/Views/Shared/_SlidShow.cshtml", LoadSliderArticles(SlideId));
        }

        [ChildActionOnly]
        public ActionResult HomeArticles(int? page)
        {
            InsertSiteStatic(ObjectId.Empty, ObjectId.Empty, "HomeStore");
            var pageNumber = page ?? 1;
            LoadArticlesAndStoresData(pageNumber);
            return PartialView("~/Views/Shared/_HomeArticles.cshtml");
        }
        //private void CreateArticleAllList(int page,   long articlecount)
        //{
        //    List<ArticleWithLikeDislikeAndComments> aaList = new List<ArticleWithLikeDislikeAndComments>();
        //    string strHostName = "";
        //    strHostName = Dns.GetHostName();
        //    IPHostEntry ipEntry = Dns.GetHostEntry(strHostName);
        //    string ipaddress = Convert.ToString(ipEntry.AddressList[1]);

        //    LikeDislikeArticle likedislike = new LikeDislikeArticle();

        //    Group group = new Group();
        //    List<Group> g_List = group.LoadDataAll();
        //    List<Group> group_List = new List<Group>();

        //    ArticleGroups ag = new ArticleGroups();
        //    List<ArticleGroups> articleGroup_List = new List<ArticleGroups>();
        //    articleGroup_List = ag.LoadDataAll();

        //    List<Group> list_Group = ag.LoadDataAllGroupsWithArticle();
        //    for (int i = 0; i < list_Group.Count; i++)
        //    {
        //        if (list_Group[i].Name == "تبلیغات" || list_Group[i].Name == "اسلاید شو")
        //        {
        //            list_Group.RemoveAt(i);
        //            i = i - 1;
        //        }
        //    }
        //    for (int i = 0; i < g_List.Count; i++)
        //    {
        //        group_List.Add(g_List[i]);
        //    }

        //    List<ArticleGalary> articleGalaryList = new List<ArticleGalary>();
        //    Articles articleAll = new Articles();
        //    ArticleComment comment = new ArticleComment();
        //    List<ArticleComment> comment_list = comment.LoadDataAll();
        //    List<ArticleComment> articleComments = new List<ArticleComment>();
        //    ArticleGalary galary = new ArticleGalary();


        //    //------------------------------ تبلیغات  ------------------
        //    Advertizements advertizement = new Advertizements();
        //    List<Advertizements> advertizementTopData = new List<Advertizements>();
        //    advertizementTopData = advertizement.LoadTopFourData();
        //    List<Advertizements> advertizementBottomData = new List<Advertizements>();
        //    advertizementBottomData = advertizement.LoadTopTwoData();
        //    //----------------------------------------------------------

        //    List<Articles> allSlideShowArticle = Articles.LoadArticlesByGroupId(new ObjectId("5a526a33e290b819dc102a35"));

        //    for (int r = 0; r < displayArticles.Count; r++)
        //    {
        //        Articles al = displayArticles[r];

        //        var gal = galary.LoadByArticleId(al.Id);
        //        if (gal != null)
        //            articleGalaryList.Add(gal);

        //        List<ArticleGroups> articleGroups = new List<ArticleGroups>();
        //        for (int j = 0; j < articleGroup_List.Count; j++)
        //        {
        //            if (articleGroup_List[j].ArticleId == al.Id)
        //            {
        //                articleGroups.Add(articleGroup_List[j]);
        //            }
        //        }
        //        int likesCount = 0;
        //        int dislikesCount = 0;
        //        foreach (var item in likedislike.LoadDataByArticleId(al.Id))
        //        {
        //            likesCount += item.LikeCount;
        //            dislikesCount += item.DislikeCount;
        //        }

        //        LikeDislikeArticle ldarticle = new LikeDislikeArticle
        //        {
        //            ArticleId = al.Id,
        //            DislikeCount = dislikesCount,
        //            LikeCount = likesCount,
        //            UserIp = ""
        //        };
        //        for (int j = 0; j < comment_list.Count; j++)
        //        {
        //            if (comment_list[j].ArticleId == al.Id)
        //            {
        //                articleComments.Add(comment_list[j]);
        //            }
        //        }
        //        int commentsCount = articleComments.Count;
        //        ArticleWithLikeDislikeAndComments aa = new ArticleWithLikeDislikeAndComments
        //        {
        //            Article = al,
        //            LikeDislike = ldarticle,
        //            ArticleComments = articleComments,
        //            Comment = comment,
        //            ArticleGalary = articleGalaryList,
        //            ArticleGroupsData = articleGroups
        //        };
        //        aaList.Add(aa);
        //    }
        //    int articlePerPage = 10;
        //    for (int i = 0; i < articlecount; i++)
        //    {
        //        if (i < (page * articlePerPage))
        //        {
        //            if (i >= ((page - 1) * articlePerPage))
        //            {
        //            }
        //            else
        //            {
        //                aaList.Insert(0, null);
        //            }
        //        }
        //        else
        //        {
        //            aaList.Add(null);
        //        }
        //    }
        //    ArticleListComplete articleList = new ArticleListComplete
        //    {
        //        ArticleList = aaList,
        //        AdvertizementTop = advertizementTopData,
        //        AdvertizementBottom = advertizementBottomData,
        //        GroupList = group_List,
        //        ArticleSlideShowList = allSlideShowArticle,
        //        TreeGroup = list_Group
        //    };
        //    IQueryable<ArticleWithLikeDislikeAndComments> IQ_List_Article = articleList.ArticleList.AsQueryable();
        //    var onePageOfProducts = IQ_List_Article.ToPagedList(page, articlePerPage); // will only contain 25 products max because of the pageSize
        //    ViewBag.ArticleDataForPageingAndView = onePageOfProducts;

        //    Stores st = new Stores();
        //    List<Stores> StoreSlideShow = new List<Stores>();
        //    StoreSlideShow = st.loadTopTwentyStoriesForSlide();
        //    ViewBag.StoreDataForSlideShow = StoreSlideShow;
        //    ViewBag.AllData = articleList;
        //}

        private void LoadArticlesAndStoresData(int pageNumber)
        {
            StoreListComplete storeComplete = new StoreListComplete();
            ArticleListComplete articleList = new ArticleListComplete();
            List<StoreWithLikeDislikeAndComments> storeWithCommentsData = new List<StoreWithLikeDislikeAndComments>();
           // List<ArticleWithLikeDislikeAndComments> aaList = new List<ArticleWithLikeDislikeAndComments>();
            List<Stores> list_StoresForSlideShow = new List<Stores>();

            LayoutLoader.CreateArticlesAndStoresData( 
                out storeWithCommentsData,
              
                out articleList,
                out list_StoresForSlideShow
                , Stores.LoadAllStoresFromTodayByPageNumber(pageNumber), Stores.GetNumberOfStores());

           // IQueryable<ArticleWithLikeDislikeAndComments> IQ_List_Articles = aaList.AsQueryable();

CGSilent/Areas/Store/Views/StoreAdmin/DeleteStore.cshtml
@model CGSilent.Models.Stores

@{
    ViewBag.Title = "حذف محصول";
    Layout = "~/Areas/Management/Views/Shared/_Management.cshtml";
}

<div class="container-fluid arrow light-bg">
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        using (Html.BeginForm("DeleteStore", "StoreAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <h2 class="TitleStyle">حذف محصول</h2>
            <div>
                <hr />
                @Html.HiddenFor(model => model.ImagePath, new { @id = "hide_ImagePath" })
                @Html.HiddenFor(model => model.ImageId, new { @id = "hide_ImageId" })

                <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ArticleHeader">
                    @Model.Title
                </aside>
                <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ArticleBody ">
                    <aside class="ArticleTitleBar">
                        <aside class="col-lg-2 col-md-2 col-sm-2 col-xs-2 Icon">
                            <img src="~/Content/Images/All/Author.png" class="ImageIcon" />
                            @Model.Author
                        </aside>
                        <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1 Icon">
                            <img src="~/Content/Images/All/Clock.png" class="ImageIcon" />
                            @{ string[] datetime = Model.CreatedDate.Split('T');

                                <span>@datetime[1]</span>
                            }
                        </aside>
                        <aside class="col-lg-2 col-md-2 col-sm-2 col-xs-2 Icon">
                            <img src="~/Content/Images/All/Calender.png" class="ImageIcon" />
                            <span>@datetime[0]</span>
                        </aside>
                        <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1 Icon">
                            <img src="~/Content/Images/All/Sharp.png" class="ImageIcon" />
                            @Model.StoreNumber
                        </aside>
                    </aside>
                    <aside class="row" id="div_ArticleImage">
                        <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1 "></aside>
                        <aside class="col-lg-10 col-md-10 col-sm-10 col-xs-10 ">
                            <img class="img-responsive ArticleImage" src="@Url.Content(Model.ImagePath)" />
                            <aside class="row summery" id="div_Summery">
                                @Model.Summery
                            </aside>
                        </aside>

                        <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1 "></aside>
                    </aside>
                    <aside class="row" id="div_ArticleImage">
                        <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1 "></aside>
                        <aside class="col-lg-10 col-md-10 col-sm-10 col-xs-10 ">
                            <aside class="row summery" id="div_Description">
                                @Html.Raw(Model.Description)
                            </aside>
                        </aside>

                        <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1 "></aside>
                    </aside>
                </aside>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 div_articleManageItem_Seperat">
                        <input type="submit" value="حذف" class="btn btn-default ButtonStyle" /> |
                        @Html.ActionLink("بازگشت به لیست ", "Index", new { area = "store" })
                    </aside>
                    <div style="clear:both; height:30px;"></div>
                }
            </div>
                                    }
                                }
                                else
                                {
                                    <span> شما مجوز دسترسی به این صفحه را ندارید.</span>
                                }

</div>

CGSilent/Areas/Store/Views/StoreAdmin/DetailAndComment.cshtml
@using CGSilent.Models

@{
    ViewBag.Title = "DetailArticle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>جزییات خبر</h2>

<div>

    @Html.Partial("DetailArticle", new ArticleWithLikeDislike())
    @Html.Partial("_ArticleComments", new ArticleWithLikeDislike())


</div>

CGSilent/Areas/Store/Views/StoreAdmin/StoreList.cshtml
@{
    ViewBag.Title = "فروشگاه";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using PagedList.Mvc; @*//import this so we get our HTML Helper*@
@using PagedList; @*//import this so we can cast our list to IPagedList (only necessary because ViewBag is dynamic)*@

<link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Style/Article.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Style/Register.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Style/Store.css")" rel="stylesheet" />

<script type="text/javascript">
    function DisableButton(id) {

    }
</script>

<style>
    hr {
        border: 1px solid #e9f4f8;
        margin: 0px;
    }
</style>


@using (Html.BeginForm("Index", "ArticleAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <p class="text-right container">
            @Html.ActionLink("ثبت محصول", "AddStore", "", new { @class = "addicon", title = "ثبت محصول جدید" })
        </p>
        <br />
    }
    <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <aside id="div_title" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 registerTitle">
            <aside class="col-lg-2 col-md-2 col-sm-2 col-xs-2 registerheader" style="padding: 0px !important; padding-left:18PX !important;">فروشگاه</aside>
            <aside class="col-lg-10 col-md-10 col-sm-10 col-xs-10 leftsideRegisterHeader"></aside>
        </aside>
    </aside>
    <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="height:60px;"></aside>
    <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="margin-bottom:20px;">
        @foreach (var item in ViewBag.StoreDataForPageingAndView)
        {
            <aside class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="margin-bottom:20px;">
                <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding:0px !important;">
                        <img class="StoreImage" src="@Url.Content(item.Store.ImagePath)" />
                    </aside>
                    <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center storeTitle">
                        <aside class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></aside>
                        <aside class="col-lg-6 col-md-6 col-sm-6 col-xs-6 div_title">
                            <a class="storeTitle" target="_blank" href=@Url.Action("DetailStore", "StoreAdmin", routeValues: new { area = "store", item.Store.Id })>
                                @item.Store.Title
                            </a>
                        </aside>
                        <aside class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></aside>
                    </aside>
                    <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 div_storedescription">
                        <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                            <img src="~/Content/Images/Store/CDIcon.png" />
                            <span class="storedescription">@item.Store.Summery</span>
                        </aside>
                        <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center" style="margin-top:5px; margin-bottom:5px;">
                            <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></aside>
                            <aside class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                <aside class="col-lg-9 col-md-9 col-sm-9 col-xs-9 text-center pull-left" style="margin:0px !important;padding:0px !important;">
                                    <div style="width:100%; height:30px; background-color:#bdbec0; color:#101a22; line-height:25px; font-weight:bold;">@item.Store.Price</div>
                                </aside>
                                <aside class="col-lg-3 col-md-3 col-sm-3 col-xs-3 text-center pull-right" style="margin:0px !important;padding:0px !important;">
                                    <div style="width:100%; height:30px; background-color:#101a22; color:#fff; line-height:25px; font-weight:bold;">مبلغ</div>
                                </aside>
                            </aside>
                            <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></aside>
                        </aside>
                        <aside class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                            <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></aside>
                            <aside class="col-lg-10 col-md-10 col-sm-10 col-xs-10 text-center">
                                <img src="~/Content/Images/Store/basket.png" />
                            </aside>
                            <aside class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></aside>
                        </aside>
                    </aside>
                </aside>
            </aside>
        }
    </aside>
}
@Html.PagedListPager((IPagedList)ViewBag.StoreDataForPageingAndView, page => Url.Action("Index", "StoreAdmin", new { page }))

<script>
    $(document).ready(function () {
        var lastpagetext = $(".PagedList-skipToLast a").text();
        if (lastpagetext == "»»") {
            var pagenumber = $(".PagedList-skipToLast a").attr("href");
            pagenumber = pagenumber.substring(7);
            $(".PagedList-skipToLast a").text(pagenumber);
        }
    });
</script>

CGSilent/Areas/Store/Views/StoreAdmin/ViewArticle.cshtml
@{
    ViewBag.Title = "ViewArticle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ViewArticle</h2>

@Html.Partial("_DetailArticle")

<br />
@Html.Partial("_ArticleComments")

CGSilent/Areas/Store/Views/StoreAdmin/_ArticleComments.cshtml
@model  IList<CGSilent.Models.ArticleComment>
 
@if (Request.IsAuthenticated)
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ArticleComment</h4>
        <hr />
        @foreach (var item in Model)
            {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => item.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => item.UserID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.UserID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => item.CommentBody, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => item.CommentBody, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.CommentBody, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => item.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => item.Answer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.Answer, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => item.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => item.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => item.UpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => item.UpdateDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.UpdateDate, "", new { @class = "text-danger" })
                </div>
            </div>
            }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
}
else
{
    <div>
        شما مجوز لازم برای درج نظر ندارید. برای درج نظر خود در سایت ثبت نام نمایید. با تشکر
    </div>
}